export const depPorts = [
    { value: "AABENRAA, DENMARK	DK AAB	Denmark", index: "0" },
    { value: "ABERDEEN, WA	US GHR	United States of America", index: "1" },
    { value: "ABIDJAN, COTE D'IVOIRE	CI ABJ	Cote D'ivoire", index: "2" },
    {
      value: "ABU KAMMASH, LIBYAN ARAB JAMAHIRIYA	LY ABK	Libyan Arab Jamahiriya",
      index: "3",
    },
    { value: "ACAJUTLA, EL SALVADOR	SV AQJ	El Salvador", index: "4" },
    { value: "ACAPULCO, MEXICO	MX ACA	Mexico", index: "5" },
    { value: "ADELAIDE, AUSTRALIA	AU ADL	Australia", index: "6" },
    { value: "ADEN, YEMEN	YM ADE	Yemen", index: "7" },
    {
      value: "AL BAYDA, LIBYAN ARAB JAMAHIRIYA	LY ABA	Libyan Arab Jamahiriya",
      index: "8",
    },
    {
      value: "AL KHUMS, LIBYAN ARAB JAMAHIRIYA	LY KHO	Libyan Arab Jamahiriya",
      index: "9",
    },
    { value: "ALAMEDA, CA	US NGZ	United States of America", index: "10" },
    { value: "AL'AQABAH, JORDAN	JO AQJ	Jordan", index: "11" },
    { value: "ALBANIA	AL ***	Albania", index: "12" },
    { value: "ALBANY, AUSTRALIA	AU ALH	Australia", index: "13" },
    { value: "ALGERIA	DZ ***	Algeria", index: "14" },
    { value: "AMERICAN SAMOA	AS ***	American Samoa", index: "15" },
    { value: "AMPALA, HONDURAS	HN AMP	Honduras", index: "16" },
    { value: "AMSTERDAM, NETHERLANDS	NL AMS	Netherlands", index: "17" },
    { value: "AMUAY, VENEZUELA	VE AMY	Venezuela", index: "18" },
    { value: "ANACORTES, WA	US OTS	United States of America", index: "19" },
    { value: "ANCHORAGE, AK	US ANC	United States of America", index: "20" },
    { value: "ANGOLA	AO ***	Angola", index: "21" },
    { value: "ANGRA DOS REIS, BRAZIL	BR ADR	Brazil", index: "22" },
    { value: "ANTIGUA AND BARBUDA	AG ***	Antigua and Barbuda", index: "23" },
    { value: "ANTWERP, BELGIUM	BE ANR	Belgium", index: "24" },
    { value: "AOMORI, JAPAN	JP AOJ	Japan", index: "25" },
    { value: "APIA, WESTERN SAMOA	WS APW	Samoa", index: "26" },
    {
      value: "APOLLONIA, LIBYAN ARAB JAMAHIRIYA	LY APO	Libyan Arab Jamahiriya",
      index: "27",
    },
    { value: "ARGENTINA	AR ***	Argentina", index: "28" },
    { value: "ARICA, CHILE	CL ARI	Chile", index: "29" },
    { value: "ARUBA	AW ***	Aruba", index: "30" },
  
    {
      value: "AS SIDR, LIBYAN ARAB JAMAHIRIYA	LY ESI	Libyan Arab Jamahiriya",
      index: "31",
    },
    { value: "ASSENS, DENMARK	DK ASN	Denmark", index: "32" },
    { value: "ASTORIA, OR	US AST	United States of America", index: "33" },
    { value: "ASUNCION, PARAGUAY	PY ASU	Paraguay", index: "34" },
    { value: "AUCKLAND, NEW ZEALAND	NZ AKL	New Zealand", index: "35" },
    { value: "AUSTRALIA	AU ***	Australia", index: "36" },
    { value: "AVILA BEACH, CA	US CSL	United States of America", index: "37" },
    {
      value: "AZ ZAWIYAH, LIBYAN ARAB JAMAHIRIYA	LY ZAW	Libyan Arab Jamahiriya",
      index: "38",
    },
    { value: "BACOLOD, PHILIPPINES	PH BCD	Philippines", index: "39" },
    { value: "BAHAMAS	BS ***	Bahamas", index: "40" },
    { value: "BAHIA BLANCA, ARGENTINA	AR BHI	Argentina", index: "41" },
    { value: "BAHRAIN	BH ***	Bahrain", index: "42" },
    { value: "BALAO, ECUADOR	EC EBL	Ecuador", index: "43" },
    { value: "BALBOA, PANAMA	PA BLB	Panama", index: "44" },
    { value: "BALTIMORE, MD	US BAL	United States of America", index: "45" },
    { value: "BANGALORE, INDIA	IN BLR	India", index: "46" },
    { value: "BANGLADESH	BD ***	Bangladesh", index: "47" },
    { value: "BARBADOS	BB ***	Barbados", index: "48" },
    {
      value: "BARBERS POINT, HI	US NAX	United States of America",
      index: "49",
    },
    { value: "BARCELONA, SPAIN	ES BCN	Spain", index: "50" },
    {
      value: "BARDIYAH, LIBYAN ARAB JAMAHIRIYA	LY BAR	Libyan Arab Jamahiriya",
      index: "51",
    },
    { value: "BARRANQUILLA, COLOMBIA	CO BAQ	Colombia", index: "52" },
    { value: "BATON ROUGE, LA	US BTR	United States of America", index: "53" },
    { value: "BAYOVAR, PERU	PE PUB	Peru", index: "54" },
    { value: "BAYPORT, TX	US BPX	United States of America", index: "55" },
    { value: "BAYTOWN, TX	US HPY	United States of America", index: "56" },
    {
      value: "BAYUQUAN, CHINA	CN BYQ	People's Republic of China",
      index: "57",
    },
    { value: "BEAUFORT, NC	US BFO	United States of America", index: "58" },
    { value: "BEAUMONT, TX	US BPT	United States of America", index: "59" },
    { value: "BEIRUT, LEBANON	LB BEY	Lebanon", index: "60" },
    { value: "BELEM, BRAZIL	BR BEL	Brazil", index: "61" },
    { value: "BELGIUM	BE ***	Belgium", index: "62" },
    { value: "BELLINGHAM, WA	US BLI	United States of America", index: "63" },
    { value: "BENICA, CA	US BNC	United States of America", index: "64" },
    {
      value: "BINGAZI, LIBYAN ARAB JAMAHIRIYA	LY BEN	Libyan Arab Jamahiriya",
      index: "65",
    },
    { value: "BITUNG, INDONESIA	ID BIT	Indonesia", index: "66" },
    { value: "BONTANG, INDONESIA	ID BXT	Indonesia", index: "67" },
    { value: "BOSTON, MA	US BOS	United States of America", index: "68" },
    { value: "BRAZIL	BR ***	Brazil", index: "69" },
    { value: "BREMERTON, WA	US PWT	United States of America", index: "70" },
    { value: "BRISBANE, AUSTRALIA	AU BNE	Australia", index: "71" },
    { value: "BROWNSVILLE, TX	US BRO	United States of America", index: "72" },
    { value: "BRUNSWICK, GA	US SSI	United States of America", index: "73" },
    {
      value:
        "BU'AYRAT AL HASUN, LIBYAN ARAB JAMAHIRIYA	LY BUA	Libyan Arab Jamahiriya",
      index: "74",
    },
    { value: "BUENAVENTURA, COLOMBIA	CO BUN	Colombia", index: "75" },
    { value: "BUENOS AIRES, ARGENTINA	AR BUE	Argentina", index: "76" },
    { value: "BULGARIA	BG ***	Bulgaria", index: "77" },
    { value: "BUNDABERG, AUSTRALIA	AU BDB	Australia", index: "78" },
    { value: "BURNABY, CANADA	CA BUB	Canada", index: "79" },
    { value: "BUSAN, SOUTH KOREA	KR PUS	Republic of Korea", index: "80" },
    { value: "BUTTERWORTH, MALAYSIA	MY WOT	Malaysia", index: "81" },
    { value: "CABO SAN LUCAS, MEXICO	MX CSL	Mexico", index: "82" },
    { value: "CALBAYOG, PHILIPPINES	PH CBY	Philippines", index: "83" },
    { value: "CALDERA, CHILE	CL CLD	Chile", index: "84" },
    { value: "CALDERA, COSTA RICA	CR CAL	Costa Rica", index: "85" },
    { value: "CALETA CORDOBA, ARGENTINA	AR CLC	Argentina", index: "86" },
    { value: "CALETA PATILLOS, CHILE	CL CAL	Chile", index: "87" },
    { value: "CALLAO, PERU	PE CLL	Peru", index: "88" },
    { value: "CAM PHA, VIET NAM	VN CPH	Viet Nam", index: "89" },
    { value: "CAMDEN, NJ	US CDE	United States of America", index: "90" },
    { value: "CAMEROON	CM ***	Cameroon", index: "91" },
    { value: "CANADA	CA ***	Canada", index: "92" },
    {
      value: "CAPE CANAVERAL, FL	US CPV	United States of America",
      index: "93",
    },
    {
      value: "CAPE HINCHINBROOK, AK	US 4HB	United States of America",
      index: "94",
    },
    { value: "CARPINTERIA, CA	US CPT	United States of America", index: "95" },
    { value: "CARTAGENA, COLOMBIA	CO CTG	Colombia", index: "96" },
    {
      value: "CATALINA ISLAND, CA	US CKI	United States of America",
      index: "97",
    },
    { value: "CEBU, PHILIPPINES	PH CEB	Philippines", index: "98" },
    { value: "CEDROS ISLAND, MEXICO	MX CRI	Mexico", index: "99" },
    { value: "CEDROS, MEXICO	MX CED	Mexico", index: "100" },
    {
      value: "CHANGSHU POINT, CHINA	CN CGS	People's Republic of China",
      index: "101",
    },
    {
      value: "CHANGZHOU, CHINA	CN CZX	People's Republic of China",
      index: "102",
    },
    {
      value: "CHAOZHOU, CHINA	CN COZ	People's Republic of China",
      index: "103",
    },
    { value: "CHARLESTON, SC	US CHS	United States of America", index: "104" },
    { value: "CHEMAINUS, CANADA	CA CHM	Canada", index: "105" },
    { value: "CHENNAI, INDIA	IN MAA	India", index: "106" },
    {
      value: "CHERRY POINT, WA	US CP4	United States of America",
      index: "107",
    },
    { value: "CHIBA, JAPAN	JP CHB	Japan", index: "108" },
    { value: "CHILE	CL ***	Chile", index: "109" },
    { value: "CHIMBOTE, PERU	PE CHM	Peru", index: "110" },
    { value: "CHITA, JAPAN	JP CTA	Japan", index: "111" },
    { value: "CHITTAGONG, BANGLADESH	BD CGP	Bangladesh", index: "112" },
    { value: "CIENFUEGOS, CUBA	CU CFG	Cuba", index: "113" },
    { value: "CLATSKANIE, OR	US YCK	United States of America", index: "114" },
    { value: "COLOMBIA	CO ***	Colombia", index: "115" },
    { value: "COMODORO RIVADAVIA, ARGENTINA	AR CRD	Argentina", index: "116" },
    { value: "CONCHAN, PERU	PE CON	Peru", index: "117" },
    { value: "CONVENT, LA	US CEN	United States of America", index: "118" },
    { value: "COOS BAY, OR	US COB	United States of America", index: "119" },
    { value: "COPENHAGEN, DENMARK	DK CPH	Denmark", index: "120" },
    { value: "CORINTO, NICARAGUA	NI CIO	Nicaragua", index: "121" },
    { value: "CORONEL, CHILE	CL CNL	Chile", index: "122" },
    {
      value: "CORPUS CHRISTI, TX	US CRP	United States of America",
      index: "123",
    },
    { value: "COSTA RICA	CR ***	Costa Rica", index: "124" },
    { value: "COTE D'IVOIRE	CI ***	Cote D'ivoire", index: "125" },
    { value: "COVENAS, COLOMBIA	CO COV	Colombia", index: "126" },
    { value: "CRISTOBAL, PANAMA	PA 4CB	Panama", index: "127" },
    { value: "CROATIA	HR ***	Republic of Croatia", index: "128" },
    { value: "CROFTON, CANADA	CA CRO	Canada", index: "129" },
    { value: "CUBA	CU ***	Cuba", index: "130" },
    {
      value: "CURACAO, NETHERLANDS ANTILLES	AN CUR	Netherlands Antilles",
      index: "131",
    },
    { value: "CYPRUS	CY ***	Cyprus", index: "132" },
    {
      value: "DALIAN, CHINA	CN DLC	People's Republic of China",
      index: "133",
    },
    {
      value: "DANGJIN-GUN, SOUTH KOREA	KR TJI	Republic of Korea",
      index: "134",
    },
    {
      value: "DARNAH, LIBYAN ARAB JAMAHIRIYA	LY DRX	Libyan Arab Jamahiriya",
      index: "135",
    },
    { value: "DARWIN, AUSTRALIA	AU DRW	Australia", index: "136" },
    { value: "DAVAO, PHILIPPINES	PH DVO	Philippines", index: "137" },
    {
      value:
        "DEMOCRATIC REPUBLIC OF THE CONGO	CD ***	Congo, The Democratic Republic of The",
      index: "138",
    },
    { value: "DENMARK	DK ***	Denmark", index: "139" },
    {
      value:
        "DIEGO GARCIA, BRITISH INDIAN OCEAN TERRITORY	IO DGA	British Indian Ocean Territory",
      index: "140",
    },
    { value: "DILISKELESI, TURKEY	TR DIL	Turkey", index: "141" },
    { value: "DOMINICAN REPUBLIC	DO ***	Dominican Republic", index: "142" },
    {
      value: "DONALDSONVILLE, LA	US DNA	United States of America",
      index: "143",
    },
    { value: "DONGHAE, SOUTH KOREA	KR TGH	Republic of Korea", index: "144" },
    {
      value: "DRIFT RIVER, AK	US DRF	United States of America",
      index: "145",
    },
    { value: "DUMAI, INDONESIA	ID DUM	Indonesia", index: "146" },
    { value: "DUNCAN BAY, CANADA	CA DCN	Canada", index: "147" },
    {
      value: "DUTCH HARBOR, AK	US DUT	United States of America",
      index: "148",
    },
    { value: "ECUADOR	EC ***	Ecuador", index: "149" },
    { value: "EDMONDS, WA	US EOW	United States of America", index: "150" },
    { value: "EGYPT	EG ***	Egypt", index: "151" },
    {
      value: "EL BOURI, LIBYAN ARAB JAMAHIRIYA	LY BOU	Libyan Arab Jamahiriya",
      index: "152",
    },
    {
      value: "EL CHOMS, LIBYAN ARAB JAMAHIRIYA	LY ELK	Libyan Arab Jamahiriya",
      index: "153",
    },
    { value: "EL SALVADOR	SV ***	El Salvador", index: "154" },
    { value: "EL SEGUNDO, CA	US ELS	United States of America", index: "155" },
    { value: "ENSENADA, MEXICO	MX ESE	Mexico", index: "156" },
    { value: "EREGLI, TURKEY	TR ELI	Turkey", index: "157" },
    { value: "ESMERALDAS, ECUADOR	EC ESM	Ecuador", index: "158" },
    { value: "ESTERO BAY, CA	US ESB	United States of America", index: "159" },
    { value: "ESTONIA	EE ***	Estonia", index: "160" },
    { value: "ETHIOPIA	ET ***	Ethiopia", index: "161" },
    { value: "EUREKA, CA	US EKA	United States of America", index: "162" },
    { value: "EVERETT, WA	US PAE	United States of America", index: "163" },
    {
      value: "FANGCHENG, CHINA	CN FAN	People's Republic of China",
      index: "164",
    },
    {
      value:
        "FEDERATED STATES OF MICRONESIA	FM ***	Micronesia, Federated States of",
      index: "165",
    },
    { value: "FERNDALE, WA	US FDT	United States of America", index: "166" },
    { value: "FIJI	FJ ***	Fiji", index: "167" },
    { value: "FINLAND	FI ***	Finland", index: "168" },
    {
      value: "FORT LAUDERDALE, FL	US FLL	United States of America",
      index: "169",
    },
    {
      value: "FORT PIERCE, FL	US FPR	United States of America",
      index: "170",
    },
    { value: "FRANCE	FR ***	France", index: "171" },
    { value: "FREEPORT, BAHAMAS	BS FPO	Bahamas", index: "172" },
    { value: "FREEPORT, TX	US FPO	United States of America", index: "173" },
    { value: "FREMANTLE, AUSTRALIA	AU FRE	Australia", index: "174" },
    { value: "FRENCH POLYNESIA	PF ***	French Polynesia", index: "175" },
    { value: "FUJI, JAPAN	JP FUI	Japan", index: "176" },
    { value: "FUKISHIMA, JAPAN	JP FKF	Japan", index: "177" },
    { value: "FUKUYAMA, JAPAN	JP FKY	Japan", index: "178" },
    {
      value: "FUQING, CHINA	CN FUG	People's Republic of China",
      index: "179",
    },
    {
      value: "FUZHOU, CHINA	CN FOC	People's Republic of China",
      index: "180",
    },
    { value: "GABON	GA ***	Gabon", index: "181" },
    { value: "GALVESTON, TX	US GLS	United States of America", index: "182" },
    { value: "GAMBA, GABON	GA GAX	Gabon", index: "183" },
    {
      value: "GAOGANG, CHINA	CN GAO	People's Republic of China",
      index: "184",
    },
    { value: "GDANSK, POLAND	PL GDN	Poland", index: "185" },
    { value: "GEELONG, AUSTRALIA	AU GEX	Australia", index: "186" },
    { value: "GERALDTON, AUSTRALIA	AU GET	Australia", index: "187" },
    { value: "GERMANY	DE ***	Germany", index: "188" },
    { value: "GHENT, BELGIUM	BE GNE	Belgium", index: "189" },
    { value: "GOLD RIVER, CANADA	CA GOR	Canada", index: "190" },
    { value: "GRAMERCY, LA	US GRY	United States of America", index: "191" },
    {
      value: "GRAYS HARBOR, WA	US GHC	United States of America",
      index: "192",
    },
    { value: "GREECE	GR ***	Greece", index: "193" },
    {
      value: "GREYS HARBOR, WA	US GHC	United States of America",
      index: "194",
    },
    { value: "GUAM	GU ***	Guam", index: "195" },
    {
      value: "GUANGZHOU, CHINA	CN CAN	People's Republic of China",
      index: "196",
    },
    { value: "GUATEMALA	GT ***	Guatemala", index: "197" },
    { value: "GUAYAQUIL, ECUADOR	EC GYE	Ecuador", index: "198" },
    { value: "GUAYMAS, MEXICO	MX GYM	Mexico", index: "199" },
    { value: "GUINEA	GN ***	Guinea", index: "200" },
    { value: "GULFITO, COSTA RICA	CR GLF	Costa Rica", index: "201" },
    { value: "GULFPORT, MS	US GPT	United States of America", index: "202" },
    { value: "GUNSAN, SOUTH KOREA	KR KUV	Republic of Korea", index: "203" },
    { value: "GUYANA	GY ***	Guyana", index: "204" },
    {
      value: "GWANGYANG, SOUTH KOREA	KR KAN	Republic of Korea",
      index: "205",
    },
    { value: "HACHINOHE, JAPAN	JP HHE	Japan", index: "206" },
    { value: "HAINES, AK	US HNS	United States of America", index: "207" },
    { value: "HAKATA, JAPAN	JP HTD	Japan", index: "208" },
    { value: "HALIFAX, CANADA	CA HAL	Canada", index: "209" },
    {
      value: "HAMPTON ROADS, VA	US PHF	United States of America",
      index: "210",
    },
    { value: "HARMAC, CANADA	CA HMC	Canada", index: "211" },
    { value: "HAWK INLET, AK	US HZZ	United States of America", index: "212" },
    { value: "HIGASHIHARIMA, JAPAN	JP HHR	Japan", index: "213" },
    { value: "HIKOSHIMA, JAPAN	JP HIS	Japan", index: "214" },
    { value: "HILO, HI	US ITO	United States of America", index: "215" },
    { value: "HIROSHIMA, JAPAN	JP HIJ	Japan", index: "216" },
    { value: "HITACHINAKA, JAPAN	JP HIC	Japan", index: "217" },
    { value: "HOKUTO, JAPAN	JP HOO	Japan", index: "218" },
    { value: "HOMER, AK	US HOM	United States of America", index: "219" },
    { value: "HONDURAS	HN ***	Honduras", index: "220" },
    { value: "HONG KONG	HK ***	Hong Kong", index: "221" },
    { value: "HONOLULU, HI	US HNL	United States of America", index: "222" },
    { value: "HOQUIAM, WA	US HQM	United States of America", index: "223" },
    { value: "HOUSTON, TX	US HOU	United States of America", index: "224" },
    {
      value: "HUNGNAM, NORTH KOREA	KP HGM	Korea, Democratic People's Republic of",
      index: "225",
    },
    { value: "ICHIHARA, JAPAN	JP ICH	Japan", index: "226" },
    {
      value: "ICY STRAIT POINT / HOONAH, AK	US HNH	United States of America",
      index: "227",
    },
    { value: "ILIGAN, PHILIPPINES	PH IGN	Philippines", index: "228" },
    { value: "INCHEON, SOUTH KOREA	KR ICH	Republic of Korea", index: "229" },
    { value: "INDIA	IN ***	India", index: "230" },
    { value: "INDONESIA	ID ***	Indonesia", index: "231" },
    { value: "IQUIQUE, CHILE	CL IQQ	Chile", index: "232" },
    { value: "IRAGO, JAPAN	JP IRK	Japan", index: "233" },
    { value: "IRISH REPUBLIC	IE ***	Ireland", index: "234" },
    { value: "ISHINOMAKI, JAPAN	JP ISM	Japan", index: "235" },
    { value: "ISLA SAN MARCOS, MEXICO	MX SMI	Mexico", index: "236" },
    { value: "ISLE OF MAN	IM ***	United Kingdom", index: "237" },
    { value: "ISRAEL	IL ***	Israel", index: "238" },
    { value: "ITALY	IT ***	Italy", index: "239" },
    { value: "IWAKUNI, JAPAN	JP  IWK	Japan", index: "240" },
    { value: "IYOMISHIMA, JAPAN	JP IYM	Japan", index: "241" },
    {
      value: "JACKSONVILLE, FL	US JAX	United States of America",
      index: "242",
    },
    { value: "JAKARTA, INDONESIA	ID JKT	Indonesia", index: "243" },
    { value: "JAMAICA	JM ***	Jamaica", index: "244" },
    { value: "JAPAN	JP ***	Japan", index: "245" },
    {
      value: "JIANGYIN, CHINA	CN JIA	People's Republic of China",
      index: "246",
    },
    {
      value:
        "JOHNSON ATOLL, U.S. MINOR OUTLYING ISLANDS	UM JON	United States Minor Outlying Islands",
      index: "247",
    },
    { value: "JORDAN	JO ***	Jordan", index: "248" },
    { value: "JUBAIL, SAUDI ARABIA	SA JUB	Saudi Arabia", index: "249" },
    { value: "JUNEAU, AK	US JNU	United States of America", index: "250" },
    { value: "KAGOSHIMA, JAPAN	JP KOJ	Japan", index: "251" },
    { value: "KAHULUI, HI	US OGG	United States of America", index: "252" },
    { value: "KAKOGAWA, JAPAN	JP KGA	Japan", index: "253" },
    { value: "KALAMA, WA	US KAM	United States of America", index: "254" },
    { value: "KALUNDBORG, DENMARK	DK KAL	Denmark", index: "255" },
    { value: "KANDA, JAPAN	JP KND	Japan", index: "256" },
    { value: "KANMON, JAPAN	JP KNM	Japan", index: "257" },
    { value: "KAOHSIUNG, TAIWAN	TW KHH	Taiwan", index: "258" },
    {
      value: "KARACHI CONTAINER TERMINAL, PAKISTAN	PK KCT	Pakistan",
      index: "259",
    },
    { value: "KARACHI, PAKISTAN	PK KHI	Niue", index: "260" },
    { value: "KASHIMA, JAPAN	JP KSM	Japan", index: "261" },
    { value: "KAWAIHAE, HI	US KWH	United States of America", index: "262" },
    { value: "KAWANOE, JAPAN	JP KWN	Japan", index: "263" },
    { value: "KAWASAKI, JAPAN	JP KWS	Japan", index: "264" },
    { value: "KEELUNG, TAIWAN	TW KEL	Taiwan", index: "265" },
    { value: "KELANG	MY KEL	Malaysia", index: "266" },
    { value: "KENAI, AK	US ENA	United States of America", index: "267" },
    { value: "KENYA	KE ***	Kenya", index: "268" },
    { value: "KETCHIKAN, AK	US KTN	United States of America", index: "269" },
    { value: "KIMITSU, JAPAN	JP KMT	Japan", index: "270" },
    { value: "KINGSTON, JAMAICA	JM KIN	Jamaica", index: "271" },
    { value: "KINUURA, JAPAN	JP KNU	Japan", index: "272" },
    {
      value: "KISKA ISLAND, AK	US KIS	United States of America",
      index: "273",
    },
    { value: "KITIMAT, CANADA	CA KTM	Canada", index: "274" },
    { value: "KLAIPEDIA, LITHUANIA	LT KLI	Lithuania", index: "275" },
    { value: "KOBE, JAPAN	JP UKB	Japan", index: "276" },
    { value: "KODIAK, AK	US ADQ	United States of America", index: "277" },
    { value: "KOMATSUSHIMA, JAPAN	JP KOM	Japan", index: "278" },
    { value: "KOTA KINABALU, MALAYSIA	MY BKI	Malaysia", index: "279" },
    {
      value: "KOZMINO PORT, RUSSIAN FEDERATION	RU KZM	Russian Federation",
      index: "280",
    },
    { value: "KUANTAN, MALAYSIA	MY KUA	Malaysia", index: "281" },
    { value: "KURE, JAPAN	JP KRE	Japan", index: "282" },
    { value: "KUWAIT	KW ***	Kuwait", index: "283" },
    {
      value: "KWANGYANG, SOUTH KOREA	KR KWA	Republic of Korea",
      index: "284",
    },
    { value: "KWINANA, AUSTRALIA	AU KWI	Australia", index: "285" },
    { value: "LA LIBERTAD, ECUADOR	EC LLD	Ecuador", index: "286" },
    { value: "LA PALOMA, URAGUAY	UY LAP	Uruguay", index: "287" },
    { value: "LA PAMPILLA, PERU	PE LPP	Peru", index: "288" },
    { value: "LA PAZ, MEXICO	MX LAP	Mexico", index: "289" },
    { value: "LAE, PAPUA NEW GUINEA	PG LAE	Papua New Guinea", index: "290" },
    { value: "LAEM CHABANG, THAILAND	TH LCH	Thailand", index: "291" },
    { value: "LAHAD DATU, MALAYSIA	MY LDU	Malaysia", index: "292" },
    { value: "LAHAINA, HI	US LHN	United States of America", index: "293" },
    {
      value: "LAIZHOU, CHINA	CN LZO	People's Republic of China",
      index: "294",
    },
    {
      value: "LAKE CHARLES, LA	US LCH	United States of America",
      index: "295",
    },
    {
      value: "LANSHAN, CHINA	CN LSN	People's Republic of China",
      index: "296",
    },
    { value: "LAS VENTANAS, CHILE	CL LVS	Chile", index: "297" },
    { value: "LAUTOKA, FIJI	FJ LTK	Fiji", index: "298" },
    { value: "LAZARO CARDENAS, MEXICO	MX LZC	Mexico", index: "299" },
    { value: "LE HAVRE, FRANCE	FR LEH	France", index: "300" },
    { value: "LEBANON	LB ***	Lebanon", index: "301" },
    {
      value: "LIANYUNGANG, CHINA	CN LYG	People's Republic of China",
      index: "302",
    },
    { value: "LIBERIA	LR ***	Liberia", index: "303" },
    {
      value: "LIBYAN ARAB JAMAHIRIYA	LY ***	Libyan Arab Jamahiriya",
      index: "304",
    },
    { value: "LIMBOH TERMINAL, CAMEROON	CM LIT	Cameroon", index: "305" },
    { value: "LITHUANIA	LT ***	Lithuania", index: "306" },
    {
      value: "LIVERPOOL, UNITED KINGDOM	GB LIV	United Kingdom",
      index: "307",
    },
    { value: "LONDON, UNITED KINGDOM	GB LON	United Kingdom", index: "308" },
    { value: "LONG BEACH, CA	US LGB	United States of America", index: "309" },
    { value: "LONGVIEW, WA	US LOG	United States of America", index: "310" },
    {
      value: "LOS ANGELES, CA	US LAX	United States of America",
      index: "311",
    },
    { value: "LUCINDA, AUSTRALIA	AU LUC	Australia", index: "312" },
    { value: "LYTTELTON, NEW ZEALAND	NZ LYT	New Zealand", index: "313" },
    { value: "MACKAY, AUSTRALIA	AU MKY	Australia", index: "314" },
    { value: "MAI-LIAO, TAIWAN	TW MLI	Taiwan", index: "315" },
    { value: "MAIZURU, JAPAN	JP MAI	Japan", index: "316" },
    {
      value: "MAJURO, MARSHALL ISLANDS	MH MAJ	Marshall Islands",
      index: "317",
    },
    { value: "MALAYSIA	MY ***	Malaysia", index: "318" },
    { value: "MALTA	MT ***	Malta", index: "319" },
    { value: "MANCHESTER, WA	US MCR	United States of America", index: "320" },
    { value: "MANILA, PHILIPPINES	PH MNL	Philippines", index: "321" },
    { value: "MANTA, ECUADOR	EC MEC	Ecuador", index: "322" },
    { value: "MANZANILLO, MEXICO	MX ZLO	Mexico", index: "323" },
    {
      value: "MARCH POINT, WA	US 4MP	United States of America",
      index: "324",
    },
    {
      value: "MARSA BREGA, LIBYAN ARAB JAMAHIRIYA	LY LMQ	Libyan Arab Jamahiriya",
      index: "325",
    },
    {
      value: "MARSA EL HANIA, LIBYAN ARAB JAMAHIRIYA	LY MEH	Libyan Arab Jamahiriya",
      index: "326",
    },
    {
      value:
        "MARSA EL HARIGA, LIBYAN ARAB JAMAHIRIYA	LY MHR	Libyan Arab Jamahiriya",
      index: "327",
    },
    { value: "MARSHALL ISLANDS	MH ***	Marshall Islands", index: "328" },
    { value: "MARTINEZ, CA	US MRZ	United States of America", index: "329" },
    { value: "MASAN, SOUTH KOREA	KR MAS	Republic of Korea", index: "330" },
    { value: "MATSUURA, JAPAN	JP MTS	Japan", index: "331" },
    { value: "MATSUYAMA, JAPAN	JP MYJ	Japan", index: "332" },
    { value: "MAZATLAN, MEXICO	MX MZT	Mexico", index: "333" },
    { value: "MEJILLONES, CHILE	CL MJS	Chile", index: "334" },
    { value: "MELBOURNE, AUSTRALIA	AU MEL	Australia", index: "335" },
    {
      value: "MELITTAH, LIBYAN ARAB JAMAHIRIYA	LY MTH	Libyan Arab Jamahiriya",
      index: "336",
    },
    { value: "MERAK, INDONESIA	ID MRK	Indonesia", index: "337" },
    { value: "MERSIN, TURKEY	TR MER	Turkey", index: "338" },
    { value: "METLAKATLA, AK	US MTM	United States of America", index: "339" },
    { value: "MEXICO	MX ***	Mexico", index: "340" },
    { value: "MIAMI, FL	US MIA	United States of America", index: "341" },
    { value: "MIIKE, JAPAN	JP MII	Japan", index: "342" },
    { value: "MIKAWA, JAPAN	JP MKW	Japan", index: "343" },
    { value: "MISHIMA, JAPAN	JP MKX	Japan", index: "344" },
    { value: "MISUMI, JAPAN	JP MMI	Japan", index: "345" },
    {
      value: "MISURATA, LIBYAN ARAB JAMAHIRIYA	LY MRA	Libyan Arab Jamahiriya",
      index: "346",
    },
    { value: "MIYAZAKI, JAPAN	JP KMI	Japan", index: "347" },
    { value: "MIZUSHIMA, JAPAN	JP MIZ	Japan", index: "348" },
    { value: "MOBILE, AL	US MOB	United States of America", index: "349" },
    { value: "MOKPO, SOUTH KOREA	KR MOK	Republic of Korea", index: "350" },
    { value: "MONROE, MI	US MOI	United States of America", index: "351" },
    { value: "MONTEREY,CA	US MY3	United States of America", index: "352" },
    { value: "MOROCCO	MA ***	Morocco", index: "353" },
    { value: "MORRO BAY, CA	US MJK	United States of America", index: "354" },
    {
      value: "MOSS LANDING, CA	US MLG	United States of America",
      index: "355",
    },
    { value: "MOURILYAN, AUSTRALIA	AU MOU	Australia", index: "356" },
    { value: "MUKILTEO, WA	US MKI	United States of America", index: "357" },
    { value: "MURORAN, JAPAN	JP MUR	Japan", index: "358" },
    { value: "MUUGA, ESTONIA	EE MUG	Estonia", index: "359" },
    { value: "NADAHAMA, JAPAN	JP NAD	Japan", index: "360" },
    { value: "NAGAHAMA, JAPAN	JP NGH	Japan", index: "361" },
    { value: "NAGASAKI, JAPAN	JP NGS	Japan", index: "362" },
    { value: "NAGOYA, JAPAN	JP NGY	Japan", index: "363" },
    { value: "NAHA, JAPAN	JP NAH	Japan", index: "364" },
    {
      value: "NAKHODKA, RUSSIAN FEDERATION	RU NJK	Russian Federation",
      index: "365",
    },
    { value: "NANAIMO, CANADA	CA NNO	Canada", index: "366" },
    {
      value: "NANJING, CHINA	CN NJG	People's Republic of China",
      index: "367",
    },
    {
      value: "NANSHA, CHINA	CN NSA	People's Republic of China",
      index: "368",
    },
    {
      value: "NANTONG, CHINA	CN NTG	People's Republic of China",
      index: "369",
    },
    { value: "NAOETSU, JAPAN	JP NAO	Japan", index: "370" },
    { value: "NAPLES, ITALY	IT NAP	Italy", index: "371" },
    { value: "NAURU	NR ***	Nauru", index: "372" },
    { value: "NAWILIWILI, HI	US NIJ	United States of America", index: "373" },
    { value: "NEMRUT BAY, TURKEY	TR NEM	Turkey", index: "374" },
    { value: "NETHERLANDS	NL ***	Netherlands", index: "375" },
    {
      value: "NETHERLANDS ANTILLES	AN ***	Netherlands Antilles",
      index: "376",
    },
    { value: "NEW CALEDONIA	NC ***	New Caledonia", index: "377" },
    { value: "NEW LONDON, CT	US NLO	United States of America", index: "378" },
    {
      value: "NEW ORLEANS, LA	US MSY	United States of America",
      index: "379",
    },
    { value: "NEW WESTMINSTER, CANADA	CA NWE	Canada", index: "380" },
    {
      value: "NEW YORK CITY, NY	US NYC	United States of America",
      index: "381",
    },
    { value: "NEW ZEALAND	NZ ***	New Zealand", index: "382" },
    { value: "NEWARK, NJ	US EWR	United States of America", index: "383" },
    {
      value: "NEWPORT NEWS, VA	US NNS	United States of America",
      index: "384",
    },
    { value: "NEWPORT, OR	US NPO	United States of America", index: "385" },
    { value: "NICARAGUA	NI ***	Nicaragua", index: "386" },
    { value: "NIGERIA	NG ***	Nigeria", index: "387" },
    { value: "NIIGATA, JAPAN	JP KIJ	Japan", index: "388" },
    { value: "NIIHAMA, JAPAN	JP IHA	Japan", index: "389" },
    { value: "NIKISKI, AK	US NIK	United States of America", index: "390" },
    {
      value: "NINGBO, CHINA	CN NGB	People's Republic of China",
      index: "391",
    },
    { value: "NORFOLK, VA	US ORF	United States of America", index: "392" },
    {
      value: "NORTH KOREA	KP ***	Korea, Democratic People's Republic of",
      index: "393",
    },
    { value: "NORWAY	NO ***	Norway", index: "394" },
    {
      value: "NOVGOROD, RUSSIAN FEDERATION	RU NVR	Russian Federation",
      index: "395",
    },
    {
      value: "NOVOROSSISK, RUSSIAN FEDERATION	RU NVS	Russian Federation",
      index: "396",
    },
    { value: "NUEVA PALMIRA, URUGUAY	UY NVP	Uruguay", index: "397" },
    { value: "OAKLAND, CA	US OAK	United States of America", index: "398" },
    { value: "OCEAN FALLS, CANADA	CA OFA	Canada", index: "399" },
    { value: "OFUNATO, JAPAN	JP OFT	Japan", index: "400" },
    { value: "OGDENSBURG, NY	US OGS	United States of America", index: "401" },
    { value: "OITA, JAPAN	JP OIT	Japan", index: "402" },
    { value: "OKINAWA, JAPAN	JP OKA	Japan", index: "403" },
    { value: "OLYMPIA, WA	US OLM	United States of America", index: "404" },
    { value: "OMAN	OM ***	Oman", index: "405" },
    { value: "ONAHAMA, JAPAN	JP ONA	Japan", index: "406" },
    { value: "ONOMICHI, JAPAN	JP ONO	Japan", index: "407" },
    { value: "ORANGE, TX	US ORG	United States of America", index: "408" },
    { value: "OSAKA, JAPAN	JP OSA	Japan", index: "409" },
    { value: "OSWEGO, NY	US OSW	United States of America", index: "410" },
    { value: "OTARU, JAPAN	JP OTR	Japan", index: "411" },
    {
      value: "PACIFIC LIGHTERING AREA	US 4PL	United States of America",
      index: "412",
    },
    { value: "PAKISTAN	PK ***	Pakistan", index: "413" },
    { value: "PALM BEACH, FL	US PAB	United States of America", index: "414" },
    { value: "PANAMA	PA ***	Panama", index: "415" },
    { value: "PANAMA CANAL	PA 4CN	Panama", index: "416" },
    {
      value: "PANAMA CITY, FL	US PFN	United States of America",
      index: "417",
    },
    { value: "PANAMA LIGHTERING AREA	PA 4PL	Panama", index: "418" },
    {
      value: "PAPEETE, TAHITI, FRENCH POLYNESIA	PF PPT	French Polynesia",
      index: "419",
    },
    { value: "PAPUA NEW GUINEA	PG ***	Papua New Guinea", index: "420" },
    { value: "PARAGUAY	PY ***	Paraguay", index: "421" },
    { value: "PASCAGOULA, MS	US PGL	United States of America", index: "422" },
    {
      value: "PEARL HARBOR, HI	US PEA	United States of America",
      index: "423",
    },
    { value: "PENANG, MALAYSIA	MY PEN	Malaysia", index: "424" },
    { value: "PENSACOLA, FL	US PNS	United States of America", index: "425" },
    {
      value: "PEOPLE'S REPUBLIC OF CHINA	CN ***	People's Republic of China",
      index: "426",
    },
    { value: "PERU	PE ***	Peru", index: "427" },
    {
      value: "PHILADELPHIA, PA	US PHL	United States of America",
      index: "428",
    },
    { value: "PHILIPPINES	PH ***	Philippines", index: "429" },
    { value: "PHU MY, VIET NAM	VN PHU	Viet Nam", index: "430" },
    { value: "PITTSBURG, CA	US PBG	United States of America", index: "431" },
    { value: "PLAQUEMINE, LA	US PLQ	United States of America", index: "432" },
    { value: "POHANG, SOUTH KOREA	KR KPO	Republic of Korea", index: "433" },
    {
      value:
        "POHNPEI, FEDERATED STATES OF MICRONESIA	FM PNI	Micronesia, Federated States of",
      index: "434",
    },
    {
      value: "POINT COMFORT, TX	US PCR	United States of America",
      index: "435",
    },
    {
      value: "POINT LISAS, TRINIDAD AND TOBAGO	TT PTS	Trinidad and Tobago",
      index: "436",
    },
    {
      value: "POINT WELLS, WA	US 4PW	United States of America",
      index: "437",
    },
    { value: "POLAND	PL ***	Poland", index: "438" },
    { value: "PORT ALBERNI, CANADA	CA PAB	Canada", index: "439" },
    { value: "PORT ALICE, CANADA	CA PAC	Canada", index: "440" },
    {
      value: "PORT ANGELES, WA	US CLM	United States of America",
      index: "441",
    },
    {
      value: "Port Angeles, Washington	US CLM	United States of America",
      index: "442",
    },
    {
      value: "PORT ARTHUR, TX	US POA	United States of America",
      index: "443",
    },
    {
      value: "PORT CLARENCE, AK	US KPC	United States of America",
      index: "444",
    },
    {
      value: "PORT EVERGLADES, FL	US PEF	United States of America",
      index: "445",
    },
    {
      value: "PORT GAMBLE, WA	US PGH	United States of America",
      index: "446",
    },
    { value: "PORT HARDY, CANADA	CA PHY	Canada", index: "447" },
    {
      value: "PORT HUENEME, CA	US NTD	United States of America",
      index: "448",
    },
    {
      value: "PORT ISABEL, TX	US PIS	United States of America",
      index: "449",
    },
    { value: "PORT KEMBLA, AUSTRALIA	AU PKL	Australia", index: "450" },
    { value: "PORT KLANG, MALAYSIA	MY PKG	Malaysia", index: "451" },
    {
      value: "PORT MANATEE, FL	US PME	United States of America",
      index: "452",
    },
    { value: "PORT MCNEILL, CANADA	CA PMA	Canada", index: "453" },
    { value: "PORT MELLON, CANADA	CA PML	Canada", index: "454" },
    { value: "PORT MOODY, CANADA	CA PMO	Canada", index: "455" },
    {
      value: "PORT OF WEST ST. MARY, FRANKLIN, LA	US RNK	United States of America",
      index: "456",
    },
    {
      value: "PORT TOWNSEND, WA	US TWD	United States of America",
      index: "457",
    },
    { value: "PORTLAND, OR	US PDX	United States of America", index: "458" },
    { value: "PORTSMOUTH, NH	US PSM	United States of America", index: "459" },
    { value: "PORTUGAL	PT ***	Portugal", index: "460" },
    { value: "POWELL RIVER, CANADA	CA POW	Canada", index: "461" },
    { value: "PRINCE RUPERT, CANADA	CA PRR	Canada", index: "462" },
    { value: "PROVIDENCE, RI	US PVD	United States of America", index: "463" },
    {
      value: "PRUDHOE BAY, AK	US SCC	United States of America",
      index: "464",
    },
    { value: "PUERTO ARMUELLES, PANAMA	PA AML	Panama", index: "465" },
    { value: "PUERTO MORELOS, MEXICO	MX PMS	Mexico", index: "466" },
    { value: "PUERTO QUETZAL, GUATEMALA	GT PRQ	Guatemala", index: "467" },
    { value: "PUERTO RICO	PR ***	Puerto Rico", index: "468" },
    { value: "PUERTO VALLARTA, MEXICO	MX PVR	Mexico", index: "469" },
    { value: "PUNTARENAS, COSTA RICA	CR PAS	Costa Rica", index: "470" },
    {
      value: "PYEONGTAEK, SOUTH KOREA	KR PTK	Republic of Korea",
      index: "471",
    },
    { value: "QATAR	QA ***	Qatar", index: "472" },
    {
      value: "QINGDAO, CHINA	CN TAO	People's Republic of China",
      index: "473",
    },
    {
      value: "QINHUANGDAO, CHINA	CN SHP	People's Republic of China",
      index: "474",
    },
    {
      value: "QUANZHOU, CHINA	CN QZL	People's Republic of China",
      index: "475",
    },
    { value: "QUINTERO, CHILE	CL QTV	Chile", index: "476" },
    {
      value: "QUONSET POINT, RI	US NCO	United States of America",
      index: "477",
    },
    { value: "RAINIER, OR	US RAI	United States of America", index: "478" },
    {
      value: "RAS LANUF, LIBYAN ARAB JAMAHIRIYA	LY RLA	Libyan Arab Jamahiriya",
      index: "479",
    },
    { value: "RAS TANURA, SAUDI ARABIA	SA RTA	Saudi Arabia", index: "480" },
    { value: "RAYONG, THAILAND	TH RYG	Thailand", index: "481" },
    { value: "RECIFE, BRAZIL	BR REC	Brazil", index: "482" },
    {
      value: "REDWOOD CITY, CA	US RWC	United States of America",
      index: "483",
    },
    { value: "REPUBLIC OF BENIN	BJ ***	Benin", index: "484" },
    { value: "RICHMOND, CA	US RCH	United States of America", index: "485" },
    { value: "RICHMOND, VA	US RIC	United States of America", index: "486" },
    { value: "RIO DE JANIERO, BRAZIL	BR RIO	Brazil", index: "487" },
    {
      value: "RIZHAO, CHINA	CN RZH	People's Republic of China",
      index: "488",
    },
    { value: "ROBERTS BANK, CANADA	CA RTB	Canada", index: "489" },
    { value: "ROMANIA	RO ***	Romania", index: "490" },
    { value: "ROSARITO TERMINAL, MEXICO	MX RST	Mexico", index: "491" },
    { value: "ROTTERDAM, NETHERLANDS	NL RTM	Netherlands", index: "492" },
    { value: "ROXAS, PHILIPPINES	PH RXS	Philippines", index: "493" },
    { value: "RUSSIAN FEDERATION	RU ***	Russian Federation", index: "494" },
    { value: "SACRAMENTO, CA	US SAC	United States of America", index: "495" },
    { value: "SAGANOSEKI, JAPAN	JP SAG	Japan", index: "496" },
    {
      value: "SAINT JAMES CITY, FL	US JSY	United States of America",
      index: "497",
    },
    {
      value: "SAINT PETERSBURG PETROLESPORT	RU SPP	Russian Federation",
      index: "498",
    },
    {
      value:
        "SAINT VINCENT AND THE GRENADINES	VC ***	Saint Vincent and The Grenadines",
      index: "499",
    },
    { value: "SAKAIDE, JAPAN	JP SKD	Japan", index: "500" },
    { value: "SALAVERRY, PERU	PE SVY	Peru", index: "501" },
    { value: "SALINA CRUZ, MEXICO	MX SCX	Mexico", index: "502" },
    { value: "SAMSUN, TURKEY	TR SSX	Turkey", index: "503" },
    { value: "SAN ANTONIA, CHILE	CL SAI	Chile", index: "504" },
    { value: "SAN CARLOS, MEXICO	MX SCR	Mexico", index: "505" },
    { value: "SAN DIEGO, CA	US SAN	United States of America", index: "506" },
    {
      value: "SAN FRANCISCO, CA	US SFO	United States of America",
      index: "507",
    },
    { value: "SAN JOSE, GUATEMALA	GT SNJ	Guatemala", index: "508" },
    { value: "SAN JUAN DEL SUR	NI SJS	Nicaragua", index: "509" },
    { value: "SAN JUAN, PUERTO RICO	PR SJU	Puerto Rico", index: "510" },
    { value: "SAN LORENZO, ECUADOR	EC SLR	Ecuador", index: "511" },
    { value: "SAN LORENZO, HOUDURAS	HN SLO	Honduras", index: "512" },
    {
      value: "SAN NICOLAS DE LOS ARROYOS, ARGENTINA	AR SNS	Argentina",
      index: "513",
    },
    { value: "SAN PEDRO, ARGENTINA	AR SNP	Argentina", index: "514" },
    { value: "SAN PEDRO, CA	US SPQ	United States of America", index: "515" },
    {
      value: "SANTA BARBARA, CA	US SBA	United States of America",
      index: "516",
    },
    { value: "SANTA CRUZ, CA	US SRU	United States of America", index: "517" },
    { value: "SANTA ROSALIA, MEXICO	MX SRL	Mexico", index: "518" },
    { value: "SANTA YNEZ, CA	US SQA	United States of America", index: "519" },
    { value: "SANTOS, BRAZIL	BR SSZ	Brazil", index: "520" },
    { value: "SARROCH, ITALY	IT PFX	Italy", index: "521" },
    { value: "SASEBO, JAPAN	JP SSB	Japan", index: "522" },
    { value: "SAUDI ARABIA	SA ***	Saudi Arabia", index: "523" },
    { value: "SAVANNAH, GA	US SAV	United States of America", index: "524" },
    { value: "SEATTLE, WA	US SEA	United States of America", index: "525" },
    { value: "SECHELT, CANADA	CA YHS	Canada", index: "526" },
    { value: "SENDAI, JAPAN	JP SDJ	Japan", index: "527" },
    { value: "SENEGAL	SN ***	Senegal", index: "528" },
    { value: "SEWARD, AK	US SWD	United States of America", index: "529" },
    {
      value: "SHANGHAI, CHINA	CN SHA	People's Republic of China",
      index: "530",
    },
    {
      value: "SHEKOU, CHINA	CN SHK	People's Republic of China",
      index: "531",
    },
    {
      value: "SHENZHEN, CHINA	CN SZX	People's Republic of China",
      index: "532",
    },
    { value: "SHIBUSHI, JAPAN	JP SBS	Japan", index: "533" },
    { value: "SHIMIZU, JAPAN	JP SMZ	Japan", index: "534" },
    { value: "SHUAIBA, KUWAIT	KW SAA	Kuwait", index: "535" },
    { value: "SILLAMAE, ESTONIA	EE SLM	Estonia", index: "536" },
    { value: "SINGAPORE	SG ***	Singapore", index: "537" },
    {
      value: "SINT EUSTATIUS, NETHERLANDS ANTILLES	AN EUX	Netherlands Antilles",
      index: "538",
    },
    { value: "SINT NICOLAAS, ARUBA	AW SNL	Aruba", index: "539" },
    {
      value: "SINT-MAARTEN APT, NETHERLANS ANTILLES	AN SXM	Netherlands Antilles",
      index: "540",
    },
    {
      value: "SIRTE, LIBYAN ARAB JAMAHIRIYA	LY SRT	Libyan Arab Jamahiriya",
      index: "541",
    },
    { value: "SISIRACHA, THAILAND	TH SRI	Thailand", index: "542" },
    { value: "SITKA, AK	US SIT	United States of America", index: "543" },
    { value: "SKAGWAY, AK	US SGY	United States of America", index: "544" },
    { value: "SKIKDA, ALGERIA	DZ SKI	Algeria", index: "545" },
    { value: "SODEGAURA, JAPAN	JP SDU	Japan", index: "546" },
    {
      value: "SOUSSAH, LIBYAN ARAB JAMAHIRIYA	LY SOU	Libyan Arab Jamahiriya",
      index: "547",
    },
    { value: "SOUTH AFRICA	ZA ***	South Africa", index: "548" },
    { value: "SOUTH KOREA	KR ***	Republic of Korea", index: "549" },
    { value: "SPAIN	ES ***	Spain", index: "550" },
    { value: "SQUAMISH, CANADA	CA SQA	Canada", index: "551" },
    { value: "SRI LANKA	SL ***	Sri Lanka", index: "552" },
    {
      value: "ST. BERNARD PARISH, LA	US SBD	United States of America",
      index: "553",
    },
    {
      value: "ST. CROIX, VIRGIN ISLANDS, U.S.	VI STX	Virgin Islands, U.S.",
      index: "554",
    },
    { value: "ST. JOHN, CANADA	CA YSJ	Canada", index: "555" },
    {
      value: "ST. PETERSBURG, RUSSIAN FEDERATION	RU LED	Russian Federation",
      index: "556",
    },
    {
      value: "ST. THOMAS, VIRGIN ISLANDS, U.S.	VI STT	United States of America",
      index: "557",
    },
    { value: "STEILACOOM, WA	US SIC	United States of America", index: "558" },
    { value: "STOCKTON, CA	US SCK	United States of America", index: "559" },
    { value: "SUAO, TAIWAN	TW SUO	Taiwan", index: "560" },
    { value: "SUDAN	SD ***	Sudan", index: "561" },
    { value: "SUVA, FIJI	FJ SUV	Fiji", index: "562" },
    { value: "SWEDEN	SE ***	Sweden", index: "563" },
    { value: "SYDNEY, AUSTRALIA	AU SYD	Australia", index: "564" },
    {
      value: "SYRIAN ARAB REPUBLIC	SY ***	Syrian Arab Republic",
      index: "565",
    },
    { value: "},ABOGUILLA, PANAMA	PA TBG	Panama", index: "566" },
    { value: "},ACOMA, WA	US TIW	United States of America", index: "567" },
    {
      value: "},AGIURA, LIBYAN ARAB JAMAHIRIYA	LY TAG	Libyan Arab Jamahiriya",
      index: "568",
    },
    { value: "},AHARA, JAPAN	JP TAR	Japan", index: "569" },
    { value: "},AICHUNG, TAIWAN	TW TXG	Taiwan", index: "570" },
    { value: "},AIPEI, TAIWAN	TW TPE	Taiwan", index: "571" },
    { value: "},AIWAN	TW ***	Taiwan", index: "572" },
    {
      value: "},AIZHOU, CHINA	CN TZO	People's Republic of China",
      index: "573",
    },
    { value: "},AKEHARA, JAPAN	JP THR	Japan", index: "574" },
    { value: "},ALLINN, ESTONIA	EE TLL	Estonia", index: "575" },
    { value: "},AMPA, FL	US TPA	United States of America", index: "576" },
    {
      value: "},ANGSHAN, CHINA	CN TGS	People's Republic of China",
      index: "577",
    },
    {
      value: "},ARTOUS, SYRIAN ARAB REPUBLIC	SY TTS	Syrian Arab Republic",
      index: "578",
    },
    { value: "},AURANGA, NEW ZEALAND	NZ TRG	New Zealand", index: "579" },
    { value: "},EXAS CITY, TX	US TXT	United States of America", index: "580" },
    { value: "},HAILAND	TH ***	Thailand", index: "581" },
    { value: "},HEODORE, AL	US TEO	United States of America", index: "582" },
    {
      value: "},IANJIN XINGANG, CHINA	CN TXG	People's Republic of China",
      index: "583",
    },
    {
      value: "},OBRUK, LIBYAN ARAB JAMAHIRIYA	LY TOB	Libyan Arab Jamahiriya",
      index: "584",
    },
    { value: "},OGIAK, AK	US TGK	United States of America", index: "585" },
    { value: "},OGO	TG ***	Togo", index: "586" },
    { value: "},OKAI, JAPAN	JP TKA	Japan", index: "587" },
    { value: "},OKUYAMA, JAPAN	JP TKY	Japan", index: "588" },
    { value: "},OKYO, JAPAN	JP TYO	Japan", index: "589" },
    { value: "},OMAKOMAI, JAPAN	JP TMK	Japan", index: "590" },
    { value: "},ONGA	TO ***	Tonga", index: "591" },
    { value: "},OPOLOBAMPO, MEXICO	MX TPB	Mexico", index: "592" },
    {
      value: "},OULMEITHA, LIBYAN ARAB JAMAHIRIYA	LY TOA	Libyan Arab Jamahiriya",
      index: "593",
    },
    { value: "},OWNSVILLE, AUSTRALIA	AU TSV	Australia", index: "594" },
    { value: "},OYOHASHI, JAPAN	JP THS	Japan", index: "595" },
    { value: "},RENTON, NJ	US TTN	United States of America", index: "596" },
    { value: "},RINIDAD AND TOBAGO	TT ***	Trinidad and Tobago", index: "597" },
    {
      value: "},RIPOLI, LIBYAN ARAB JAMAHIRIYA	LY TIP	Libyan Arab Jamahiriya",
      index: "598",
    },
    { value: "},SUKUMI, JAPAN	JP TMI	Japan", index: "599" },
    { value: "},SUNEISHI, JAPAN	JP TNI	Japan", index: "600" },
    {
      value: "},UKRAH, LIBYAN ARAB JAMAHIRIYA	LY TUK	Libyan Arab Jamahiriya",
      index: "601",
    },
    { value: "},UMACO, COLOMBIA	CO TCO	Colombia", index: "602" },
    { value: "},UNISIA	TN ***	Tunisia", index: "603" },
    { value: "},URKEY	TR ***	Turkey", index: "604" },
    { value: "UBE, JAPAN	JP UBJ	Japan", index: "605" },
    { value: "UKRAINE	UA ***	Ukraine", index: "606" },
    { value: "ULSAN, SOUTH KOREA	KR USN	Republic of Korea", index: "607" },
    { value: "UNION OF MYANMAR	MM ***	Myanmar", index: "608" },
    {
      value: "UNITED ARAB EMIRATES	AE ***	United Arab Emirates",
      index: "609",
    },
    { value: "UNITED KINGDOM	GB ***	United Kingdom", index: "610" },
    { value: "URAGO, JAPAN	JP UAO	Japan", index: "611" },
    { value: "URUGUAY	UY ***	Uruguay", index: "612" },
    { value: "VALDEZ, AK	US VDZ	United States of America", index: "613" },
    { value: "VALENCIA, SPAIN	ES VLC	Spain", index: "614" },
    { value: "VALPARAISO, CHILE	CL VAP	Chile", index: "615" },
    { value: "VANCOUVER, CANADA	CA VAN	Canada", index: "616" },
    { value: "VANCOUVER, WA	US VAN	United States of America", index: "617" },
    {
      value: "VANINO, RUSSIAN FEDERATION	RU VNN	Russian Federation",
      index: "618",
    },
    { value: "VANUATU	VU ***	Vanuatu", index: "619" },
    { value: "VENEZUELA	VE ***	Venezuela", index: "620" },
    { value: "VENTURA, CA	US NVT	United States of America", index: "621" },
    { value: "VICTORIA, CANADA	CA VIC	Canada", index: "622" },
    { value: "VIET NAM	VN ***	Viet Nam", index: "623" },
    {
      value: "VLADIVOSTOK, RUSSIAN FEDERATION	RU VVO	Russian Federation",
      index: "624",
    },
    {
      value: "VOSTOCHNYY, RUSSIAN FEDERATION	RU VYP	Russian Federation",
      index: "625",
    },
    {
      value:
        "WAKE ISLAND, U.S. MINOR OUTLYING ISLANDS	UM AWK	United States Minor Outlying Islands",
      index: "626",
    },
    { value: "WELLINGTON, NEW ZEALAND	NZ WLG	New Zealand", index: "627" },
    { value: "WESTERN SAMOA	WS ***	Samoa", index: "628" },
    { value: "WHITEGATE, IRISH REPUBLIC	IE WHI	Ireland", index: "629" },
    { value: "WILHELMSHAVEN, GERMANY	DE  WVN	Germany", index: "630" },
    {
      value: "WILLAPA HARBOR, WA	US WIH	United States of America",
      index: "631",
    },
    { value: "WILLBRIDGE, OR	US 4WB	United States of America", index: "632" },
    {
      value: "WILLIAMSTON, NC	US WQX	United States of America",
      index: "633",
    },
    { value: "WILMINGTON, CA	US WTN	United States of America", index: "634" },
    { value: "WILMINGTON, DE	US ILG	United States of America", index: "635" },
    { value: "WILMINGTON, NC	US ILM	United States of America", index: "636" },
    { value: "WOODFIBRE, CANADA	CA WOO	Canada", index: "637" },
    {
      value: "XIAMEN, CHINA	CN XMN	People's Republic of China",
      index: "638",
    },
    {
      value: "XINGANG, CHINA	CN XGG	People's Republic of China",
      index: "639",
    },
    {
      value: "XINSHA, CHINA	CN XNA	People's Republic of China",
      index: "640",
    },
    {
      value: "YANGSHAN, CHINA	CN YAN	People's Republic of China",
      index: "641",
    },
    {
      value: "YANGZHOU, CHINA	CN YZH	People's Republic of China",
      index: "642",
    },
    {
      value: "YANTAI, CHINA	CN YNT	People's Republic of China",
      index: "643",
    },
    {
      value: "YANTIAN, CHINA	CN YTN	People's Republic of China",
      index: "644",
    },
    {
      value:
        "YAP, FEDERATED STATES OF MICRONESIA	FM YAP	Micronesia, Federated States of",
      index: "645",
    },
    { value: "YATSUSHIRO, JAPAN	JP YAT	Japan", index: "646" },
    { value: "YAWATA, JAPAN	JP YWT	Japan", index: "647" },
    { value: "YAWATAHAMA, JAPAN	JP YWH	Japan", index: "648" },
    { value: "YEMEN	YM ***	Yemen", index: "649" },
    { value: "YEOSU, SOUTH KOREA	KR YOS	Republic of Korea", index: "650" },
    { value: "YOKKAICHI, JAPAN	JP YKK	Japan", index: "651" },
    { value: "YOKOHAMA, JAPAN	JP YOK	Japan", index: "652" },
    { value: "YOKOSUKA, JAPAN	JP YOS	Japan", index: "653" },
    { value: "ZAMBIA	ZM ***	Zambia", index: "654" },
    { value: "ZAMBOANGA, PHILIPPINES	PH ZAM	Philippines", index: "655" },
    {
      value: "ZHANGJIAGANG, CHINA	CN ZJG	People's Republic of China",
      index: "656",
    },
    {
      value: "ZHANJIANG, CHINA	CN ZNG	People's Republic of China",
      index: "657",
    },
    {
      value: "ZHENJIANG, CHINA	CN ZHE	People's Republic of China",
      index: "658",
    },
    {
      value: "ZHOUSHAN, CHINA	CN ZOS	People's Republic of China",
      index: "659",
    },
    {
      value: "ZHUHAI, CHINA	CN ZUH	People's Republic of China",
      index: "660",
    },
    {
      value: "ZLITEN, LIBYAN ARAB JAMAHIRIYA	LY ZLI	Libyan Arab Jamahiriya",
      index: "661",
    },
    {
      value: "ZUARA, LIBYAN ARAB JAMAHIRIYA	LY ZUA	Libyan Arab Jamahiriya",
      index: "662",
    },
  ];

  export const arrPorts = [
    { value: "GTPRQ - Puerto Quetzal, Guatemala - Pacific", index: "0" },
    { value: "GTPBR - Puerto Barrios, Guatemala - Caribbean", index: "1" },
    {
      value: "GTSTC - Santo Tomás de Castilla, Guatemala - Caribbean",
      index: "2",
    },
    { value: "SVAQJ - Acajutla, El Salvador - Pacific", index: "3" },
    { value: "SVLLD - La Libertad, El Salvador - Pacific", index: "4" },
    { value: "HNPCR - Puerto Cortés, Honduras - Caribbean", index: "5" },
    { value: "NICIO - Puerto Corinto, Nicaragua - Pacific", index: "6" },
    { value: "CRCAL - Puerto Caldera, Costa Rica - Pacific", index: "7" },
    {
      value: "CRPMN - Puerto Moín (Limón), Costa Rica - Caribbean",
      index: "8",
    },
    { value: "PAONX - Colón, Panamá - Caribbean", index: "9" },
    {
      value: "PACTB - Cristobal Terminal - Panamá - Caribbean",
      index: "10",
    },
    {
      value: "PAMIT - Manzanillo Terminal - Panamá - Caribbean",
      index: "11",
    },
    { value: "PABLB - Puerto Balboa - Panamá - Pacific", index: "12" },
  ];
  
  export const termsOfTrade = [
    { value: "Incoterm", index: "99" },
    { value: "EXW", index: "0" },
    { value: "FCA", index: "1" },
    { value: "CPT", index: "2" },
    { value: "CIP", index: "3" },
    { value: "DAP", index: "4" },
    { value: "DPU", index: "5" },
    { value: "DDP", index: "6" },
    { value: "FAS", index: "7" },
    { value: "FOB", index: "8" },
    { value: "CFR", index: "9" },
    { value: "CIF", index: "10" },
  ];
export const country = [
    { value: "Guatemala", index: "0" },
    { value: "El Salvador", index: "1" },
    { value: "Nicaragua", index: "2" },
    { value: "Costa Rica", index: "3" },
    { value: "Panama", index: "4" },
    { value: "Honduras", index: "5" },
  ];
    